name: DEPLOY TO DEV

on:
  push:
    branches: 'main'

jobs:
  # lint_and_test:
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Use node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: '16.x'
  #     - run: npm ci
  #     - run: npm run jest:coverage
  #
  build_and_pub:
    runs-on: ubuntu-latest
    # needs: [lint_and_test]
    env:
      LOGIN: saymurrmeow
      NAME: insight-web-client

    steps:
      - name: Get release tag
        run: echo "RELEASE_SHA_TAG=`echo dev-${GITHUB_SHA} | cut -c1-12`" >> $GITHUB_ENV
      - name: Login to docker
        run: echo ${{ secrets.DOCKER_PWD }} | docker login -u ${{ secrets.DOCKER_LOGIN }} --password-stdin
      - uses: actions/checkout@v3
      - name: Build image
        run: docker build -t $LOGIN/$NAME:$RELEASE_SHA_TAG -f Dockerfile .
      - name: Push image
        run: docker push $LOGIN/$NAME:$RELEASE_SHA_TAG
